"""
Query Classifier - Smart Routing for Cost Optimization
Classifies user queries into simple vs complex to route appropriately.

QUERY TYPES:
- SIMPLE: Can be answered with Pandas directly (no AI needed)
- CACHED: Can use cached templates from Vector DB
- COMPLEX: Requires AI reasoning (Gemini call)

This reduces API costs by 60-80% for typical usage patterns.
"""

import re
import logging
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


# Simple query patterns that can be answered with Pandas
# Format: (pattern_regex, query_type, pandas_template)
SIMPLE_PATTERNS = [
    # Count queries
    (r"^how many (rows|records|entries)( are there)?(\?)?$", "count_rows", "df.shape[0]"),
    (r"^(count|number of) (rows|records|entries)(\?)?$", "count_rows", "df.shape[0]"),
    (r"^how many columns(\?)?$", "count_cols", "df.shape[1]"),
    (r"^(what are|list|show) (the )?columns(\?)?$", "list_columns", "df.columns.tolist()"),
    
    # Count by category
    (r"^(count|how many) (.*) (by|per|for each) (.+)(\?)?$", "count_by", "df['{col}'].value_counts()"),
    (r"^(count|number of) (.+) (by|in each|per) (.+)(\?)?$", "count_by", "df['{col}'].value_counts()"),
    
    # Sum/Total queries
    (r"^(what is |what's )?(the )?(total|sum) (of )?(.+)(\?)?$", "sum", "df['{col}'].sum()"),
    (r"^sum (of )?(.+)(\?)?$", "sum", "df['{col}'].sum()"),
    
    # Average/Mean queries
    (r"^(what is |what's )?(the )?(average|mean|avg) (of )?(.+)(\?)?$", "average", "df['{col}'].mean()"),
    (r"^average (of )?(.+)(\?)?$", "average", "df['{col}'].mean()"),
    
    # Min/Max queries
    (r"^(what is |what's )?(the )?(max|maximum|highest|largest) (of |value of )?(.+)(\?)?$", "max", "df['{col}'].max()"),
    (r"^(what is |what's )?(the )?(min|minimum|lowest|smallest) (of |value of )?(.+)(\?)?$", "min", "df['{col}'].min()"),
    
    # Top N queries
    (r"^(show |list )?(the )?(top|first) (\d+) (.+)(\?)?$", "top_n", "df['{col}'].value_counts().head({n})"),
    (r"^(show |list )?(the )?(bottom|last) (\d+) (.+)(\?)?$", "bottom_n", "df['{col}'].value_counts().tail({n})"),
    
    # Unique values
    (r"^(what are |list )?(the )?(unique|distinct) (values of |values in )?(.+)(\?)?$", "unique", "df['{col}'].unique()"),
    (r"^how many unique (.+)(\?)?$", "unique_count", "df['{col}'].nunique()"),
    
    # Data summary
    (r"^(show |give )?(me )?(a )?summary(\?)?$", "summary", "df.describe()"),
    (r"^describe (the )?data(\?)?$", "summary", "df.describe()"),
    (r"^(data |dataset )?info(\?)?$", "info", "df.info()"),
]

# Patterns that indicate complex queries requiring AI
COMPLEX_INDICATORS = [
    r"\b(analyze|insight|explain|why|recommend|suggest|compare|contrast|relationship|correlation)\b",
    r"\b(trend|pattern|outlier|anomaly|forecast|predict|what if)\b",
    r"\b(impact|effect|cause|driver|factor|influence)\b",
    r"\b(segment|cluster|group by multiple|pivot)\b",
    r"\b(best|worst|optimize|improve|strategy)\b",
    r"\b(month over month|year over year|growth rate|percentage change)\b",
    r"\b(by each|by category|by product|by region|by customer|per category|per product|generated by)\b",
    r"\b(group|breakdown|distribution|across)\b",
    r"\b(age group|age bracket|age range)\b",
]

# Keywords that suggest cacheable template queries
TEMPLATE_KEYWORDS = {
    "sales": ["revenue by region", "top products", "sales trend", "order analysis"],
    "marketing": ["campaign roi", "conversion funnel", "cost per", "channel performance"],
    "hr": ["headcount by", "average tenure", "turnover rate", "salary distribution"],
    "financial": ["budget vs actual", "profit margin", "expense breakdown", "cash flow"],
    "survey": ["satisfaction score", "nps", "sentiment", "response rate"],
    "product": ["feature usage", "retention", "churn rate", "user engagement"],
    "business": ["kpi", "performance", "target vs actual", "growth"],
    "operations": ["efficiency", "throughput", "cycle time", "sla compliance"],
}


class QueryClassifier:
    """
    Classifies user queries for smart routing.
    
    Query classification flow:
    1. Check if query matches SIMPLE patterns → Execute with Pandas
    2. Check if query matches TEMPLATE keywords → Use cached template
    3. Otherwise → Route to AI (Gemini)
    """
    
    def __init__(self, available_columns: List[str] = None):
        """
        Initialize classifier with available columns.
        
        Args:
            available_columns: List of column names in the current dataset
        """
        self.available_columns = [col.lower() for col in (available_columns or [])]
        self.column_map = {col.lower(): col for col in (available_columns or [])}
        
        # Compile regex patterns for efficiency
        self.simple_patterns = [(re.compile(p, re.IGNORECASE), t, template) 
                                 for p, t, template in SIMPLE_PATTERNS]
        self.complex_patterns = [re.compile(p, re.IGNORECASE) for p in COMPLEX_INDICATORS]
    
    def classify(self, query: str, domain: str = "general") -> Dict:
        """
        Classify a user query.
        
        Args:
            query: User's natural language query
            domain: Detected data domain (for template matching)
            
        Returns:
            dict with:
                - query_type: 'simple' | 'template' | 'complex'
                - confidence: float (0-1)
                - pandas_code: str (if simple)
                - template_key: str (if template)
                - reason: str (explanation)
        """
        query_lower = query.lower().strip()
        
        # Step 1: Check for complex indicators FIRST (prioritize AI for these)
        # This prevents "total revenue by category" from being treated as simple SUM
        if self._has_complex_indicators(query_lower):
            return {
                "query_type": "complex",
                "confidence": 0.9,
                "reason": "Query contains analytical keywords requiring AI reasoning"
            }
        
        # Step 2: Check for simple Pandas queries
        simple_result = self._check_simple_pattern(query_lower)
        if simple_result:
            return simple_result
        
        # Step 3 (legacy check - should not be reached now):
        if self._has_complex_indicators(query_lower):
            return {
                "query_type": "complex",
                "confidence": 0.9,
                "reason": "Query contains analytical keywords requiring AI reasoning"
            }
        
        # Step 3: Check for template matches
        template_result = self._check_template_match(query_lower, domain)
        if template_result:
            return template_result
        
        # Default: Complex (needs AI)
        return {
            "query_type": "complex",
            "confidence": 0.5,
            "reason": "Query requires AI interpretation"
        }
    
    def _check_simple_pattern(self, query: str) -> Optional[Dict]:
        """Check if query matches a simple Pandas pattern."""
        for pattern, query_type, template in self.simple_patterns:
            match = pattern.match(query)
            if match:
                # Extract column name if present
                groups = match.groups()
                col_name = self._find_column_in_query(query)
                
                # Build Pandas code
                pandas_code = template
                if '{col}' in template:
                    if col_name:
                        pandas_code = template.replace('{col}', col_name)
                    else:
                        # Can't determine column - route to AI
                        return None
                
                # Handle numeric parameters (e.g., top N)
                if '{n}' in pandas_code:
                    for g in groups:
                        if g and g.isdigit():
                            pandas_code = pandas_code.replace('{n}', g)
                            break
                
                return {
                    "query_type": "simple",
                    "confidence": 0.95,
                    "pandas_code": pandas_code,
                    "operation": query_type,
                    "column": col_name,
                    "reason": f"Simple {query_type} operation detected"
                }
        
        return None
    
    def _find_column_in_query(self, query: str) -> Optional[str]:
        """
        Find a column name mentioned in the query.
        Uses fuzzy matching against available columns.
        """
        if not self.available_columns:
            return None
        
        query_words = set(query.lower().split())
        
        # Direct match
        for col_lower, col_original in self.column_map.items():
            # Check for exact match
            if col_lower in query_words:
                return col_original
            
            # Check for partial match (column name without underscores)
            col_clean = col_lower.replace('_', '')
            query_clean = query.replace(' ', '').replace('_', '')
            if col_clean in query_clean:
                return col_original
        
        return None
    
    def _has_complex_indicators(self, query: str) -> bool:
        """Check if query contains complex analytical keywords."""
        for pattern in self.complex_patterns:
            if pattern.search(query):
                return True
        return False
    
    def _check_template_match(self, query: str, domain: str) -> Optional[Dict]:
        """Check if query matches a cacheable template."""
        domain_templates = TEMPLATE_KEYWORDS.get(domain, [])
        
        for template_key in domain_templates:
            # Fuzzy match: check if all words in template are in query
            template_words = set(template_key.split())
            query_words = set(query.split())
            
            if template_words.issubset(query_words) or template_key in query:
                return {
                    "query_type": "template",
                    "confidence": 0.8,
                    "template_key": template_key,
                    "domain": domain,
                    "reason": f"Matches '{template_key}' template for {domain} domain"
                }
        
        return None
    
    def get_query_stats(self, queries: List[str], domain: str = "general") -> Dict:
        """
        Analyze a batch of queries and return classification statistics.
        Useful for estimating cost savings.
        
        Args:
            queries: List of user queries
            domain: Data domain
            
        Returns:
            dict with counts and percentages by query type
        """
        stats = {"simple": 0, "template": 0, "complex": 0, "total": len(queries)}
        
        for query in queries:
            result = self.classify(query, domain)
            stats[result["query_type"]] += 1
        
        # Calculate percentages
        if stats["total"] > 0:
            for key in ["simple", "template", "complex"]:
                stats[f"{key}_pct"] = round(100 * stats[key] / stats["total"], 1)
        
        # Estimate cost savings (simple and template don't need AI calls)
        stats["ai_calls_needed"] = stats["complex"]
        stats["ai_calls_saved"] = stats["simple"] + stats["template"]
        stats["cost_savings_pct"] = stats.get("simple_pct", 0) + stats.get("template_pct", 0)
        
        return stats


def classify_query(query: str, columns: List[str] = None, domain: str = "general") -> Dict:
    """
    Convenience function to classify a single query.
    
    Args:
        query: User's natural language query
        columns: Available column names
        domain: Data domain
        
    Returns:
        Classification result dict
    """
    classifier = QueryClassifier(columns)
    return classifier.classify(query, domain)


# ============= TEST =============
if __name__ == "__main__":
    # Test queries
    test_queries = [
        # Simple queries (should be Pandas)
        "how many rows?",
        "count rows",
        "what are the columns?",
        "total revenue",
        "average price",
        "top 5 products",
        "unique regions",
        "show summary",
        
        # Complex queries (should go to AI)
        "analyze the sales trend over time",
        "what factors are driving revenue growth?",
        "compare Q1 vs Q2 performance and explain the difference",
        "recommend ways to improve customer retention",
        "why are sales declining in the West region?",
        
        # Template queries (should use cached templates)
        "show revenue by region",
        "what is the conversion funnel",
        "budget vs actual comparison",
    ]
    
    classifier = QueryClassifier(["product", "revenue", "price", "region", "quantity", "date"])
    
    print("=" * 60)
    print("QUERY CLASSIFICATION TEST")
    print("=" * 60)
    
    for query in test_queries:
        result = classifier.classify(query, domain="sales")
        print(f"\n📝 Query: '{query}'")
        print(f"   Type: {result['query_type'].upper()}")
        print(f"   Confidence: {result['confidence']:.0%}")
        print(f"   Reason: {result['reason']}")
        if result.get('pandas_code'):
            print(f"   Code: {result['pandas_code']}")
    
    # Stats
    print("\n" + "=" * 60)
    print("BATCH STATISTICS")
    print("=" * 60)
    stats = classifier.get_query_stats(test_queries, domain="sales")
    print(f"Total queries: {stats['total']}")
    print(f"  Simple (Pandas): {stats['simple']} ({stats.get('simple_pct', 0)}%)")
    print(f"  Template (Cached): {stats['template']} ({stats.get('template_pct', 0)}%)")
    print(f"  Complex (AI): {stats['complex']} ({stats.get('complex_pct', 0)}%)")
    print(f"\n💰 Cost savings: ~{stats['cost_savings_pct']}% fewer AI calls!")
